### ISSUE TITLE
1-dimensional surrogate with GEKPLS

### ISSUE THREAD

**Issue by nwu63** [SMTorg/smt#174]
Hi, I'm not able to train a GE-KPLS surrogate when the input is 1-dimensional. There seems to be an implicit requirement on the surrogate being at least 2-dimensional. See:
```
import numpy as np
from smt.surrogate_models import GEKPLS
from smt.problems import NdimRosenbrock
from smt.sampling_methods import LHS

# Construction of the DOE
nsamp = 10
fun = NdimRosenbrock(ndim=1)
sampling = LHS(xlimits=fun.xlimits, criterion="m")
xt = sampling(nsamp)
yt = fun(xt)
yd = np.zeros((nsamp,1))
yd[:,0] = fun(xt, kx=0).flatten()

# Build the GEKPLS model
sm = GEKPLS(
    theta0=[1e-2], xlimits=fun.xlimits, extra_points=1, print_prediction=False
)
sm.set_training_values(xt, yt)
sm.set_training_derivatives(xt, yd[:,0], 0)
sm.train()
```

which gave the error 
```
Traceback (most recent call last):
  File "1D_test.py", line 23, in <module>
    sm.train()
  File "site-packages/smt/surrogate_models/surrogate_model.py", line 248, in train
    self._train()
  File "site-packages/smt/surrogate_models/krg_based.py", line 132, in _train
    self._new_train()
  File "site-packages/smt/surrogate_models/krg_based.py", line 93, in _new_train
    X, y = self._compute_pls(X.copy(), y.copy())
  File "site-packages/smt/surrogate_models/gekpls.py", line 56, in _compute_pls
    self.options["extra_points"],
  File "site-packages/smt/utils/kriging_utils.py", line 261, in ge_compute_pls
    _X[2, 1] += delta_x * (xlimits[1, 1] - xlimits[1, 0])
IndexError: index 1 is out of bounds for axis 1 with size 1
```

The logic in `ge_compute_pls` would suggest that 2D is the lowest that is supported. Is that a mathematical requirement or an artifact of the implementation? Thanks,

Neil

**Comment by bouhlelma** [comment]
Hi,
Yes, that's right. GE-KPLS works only for dimensions greater or equal than 2. This is because the PLS does apply only for problems with a dimension greater or equal to 2.
