### ISSUE TITLE
Errors in full factorial sampling when using weights

### ISSUE THREAD

**Issue by tjmackman** [SMTorg/smt#195]
Using the weights argument for the FullFactorial sampling class throws up a few issues (under Anaconda3-2020.02-Windows-x86_64, with smt-0.4.3-cp37-cp37m-win_amd64.whl from PyPI):

If used with an array as input for weights:
```python
Traceback (most recent call last):
  File ".\rbf.py", line 31, in <module>
    ff = smt.sampling_methods.FullFactorial(xlimits=lims, weights=np.array([ff_nx, ff_ny]))
  File "C:\Anaconda3\lib\site-packages\smt\sampling_methods\sampling_method.py", line 38, in __init__
    self.options.update(kwargs)
  File "C:\Anaconda3\lib\site-packages\smt\utils\options_dictionary.py", line 115, in update
    self[name] = dict_[name]
  File "C:\Anaconda3\lib\site-packages\smt\utils\options_dictionary.py", line 71, in __setitem__
    self._assert_valid(name, value)
  File "C:\Anaconda3\lib\site-packages\smt\utils\options_dictionary.py", line 85, in _assert_valid
    assert value in values or isinstance(
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

I've patched my own version to fix this by changing the options declare statement in the class initialisation
```python
        self.options.declare("weights", values=[None], types=[list, np.ndarray])
```
to
```python
        self.options.declare("weights", values=None, types=[list, np.ndarray])
```

If used with a list as input for weights:
```python
Traceback (most recent call last):
  File ".\rbf.py", line 32, in <module>
    ff = smt.sampling_methods.FullFactorial(xlimits=lims, weights=[ff_nx, ff_ny])
  File "C:\Anaconda3\lib\site-packages\smt\sampling_methods\sampling_method.py", line 38, in __init__
    self.options.update(kwargs)
  File "C:\Anaconda3\lib\site-packages\smt\utils\options_dictionary.py", line 115, in update
    self[name] = dict_[name]
  File "C:\Anaconda3\lib\site-packages\smt\utils\options_dictionary.py", line 71, in __setitem__
    self._assert_valid(name, value)
  File "C:\Anaconda3\lib\site-packages\smt\utils\options_dictionary.py", line 86, in _assert_valid
    value, types
TypeError: isinstance() arg 2 must be a type or tuple of types
```

Again, I've patched my own version by changing the options declare statement in the class initialisation
```python
        self.options.declare("weights", values=[None], types=[list, np.ndarray])
```
to
```python
        self.options.declare("weights", values=None, types=(list, np.ndarray))
```

Finally, fix another couple of errors (numpy module name, and a type error with /= operator) with the weight normalisation in _compute (line 41), by changing
```python
            weights /= numpy.sum(weights)
```
to
```python
            weights = weights / np.sum(weights)
```

I can try to commit a fixed version of the code if it's easier.

**Comment by relf** [comment]
Thanks! It seems you find a nest of bugs! Definitely a lack of testing. A PR will be welcomed for sure.
